<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Template for displaying products list widget
 *
 * @var $block \Magento\CatalogWidget\Block\Product\ProductsList
 */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())):?>
<?php
$_productCollection = $block->getLoadedProductCollection();

// Daily deal Helper
$_dailydealhelper =$this->helper('Smartwave\Dailydeals\Helper\Data');

$_portohelper = $this->helper('Smartwave\Porto\Helper\Data');
$_category_config = $_portohelper->getConfig('porto_settings/category');
$_category_grid_config = $_portohelper->getConfig('porto_settings/category_grid');
$_product_label_config = $_portohelper->getConfig('porto_settings/product_label');
$_lazyload = $_portohelper->getConfig('porto_settings/optimization/lazyload');
$product_type = $_category_grid_config['product_type'];

$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
?>
<?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'category_page_list';
    $hover_image = 'category_page_list-hover';
    $title = $block->getTitle() ? __($block->getTitle()) : '';
    $items = $block->getProductCollection()->getItems();
    $column_count = $this->getData("column_count");
    if($column_count == null) {
        $column_count = 4;
    }
    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
    $image_width = ($_category_config['ratio_width'])?$_category_config['ratio_width']:300;
    $image_height = ($_category_config['ratio_height'])?$_category_config['ratio_height']:300;
    $aspect_ratio = $_category_config['aspect_ratio'];
    if($aspect_ratio){
      $image_height = $image_width;
    }
?>
        <?php if ($title):?>
        <div class="block-title">
            <strong><?php /* @escapeNotVerified */ echo $title; ?></strong>
        </div>
        <?php endif ?>
        <?php /* @escapeNotVerified */ echo '<!-- ' . $image . '-->' ?>
        <div class="products-grid products-<?php /* @escapeNotVerified */ echo $mode; ?> columns<?php echo $column_count; ?> <?php /* @escapeNotVerified */ echo $mode; ?><?php if($product_type == 2): ?> no-padding divider-line<?php endif; ?><?php if($product_type == 5 || $product_type == 6 || $product_type == 7 || $product_type == 8): ?> no-padding<?php endif; ?><?php if($product_type == 6): ?> divider-line<?php endif; ?>">
            <ol class="products product-items <?php /* @escapeNotVerified */ echo $type; ?>">
                <?php $iterator = 1; ?>
                <?php foreach ($items as $_item): ?>
                    <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                    <div class="product-item-info type<?php echo $product_type; ?>" data-container="product-grid">
                        <div class="product photo product-item-photo">
                          <a href="<?php echo $_item->getProductUrl() ?>" tabindex="-1">
                              <?php
                                  if($_category_config['aspect_ratio'])
                                      $productImage = $_imagehelper->init($_item, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
                                  else
                                      $productImage = $_imagehelper->init($_item, $image)->resize($image_width, $image_height);
                                  $productImageUrl = $productImage->getUrl();
                              ?>
                                  <img class="product-image-photo default_image" src="<?php echo $productImageUrl; ?>" width="<?php echo $image_width; ?>" height="<?php echo $image_height; ?>" alt="<?php echo $productImage->getLabel(); ?>"/>
                              <?php if($_category_config['alternative_image']): ?>
                              <?php
                                  if($_category_config['aspect_ratio'])
                                      $productHoverImage = $_imagehelper->init($_item, $hover_image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
                                  else
                                      $productHoverImage = $_imagehelper->init($_item, $hover_image)->resize($image_width, $image_height);
                                  $productHoverImageUrl = $productHoverImage->getUrl();
                              ?>
                                  <?php if($productImageUrl != str_replace("/thumbnail/","/small_image/",$productHoverImageUrl)): ?>
                                  <img class="product-image-photo hover_image" src="<?php echo $productHoverImageUrl; ?>" width="<?php echo $image_width; ?>" height="<?php echo $image_height; ?>" alt="<?php echo $productHoverImage->getLabel(); ?>"/>
                                  <?php endif; ?>
                              <?php endif; ?>
                          </a>
                          <?php
                              $product_label = "";
                              if($_product_label_config['sale_label']) {
                                  if ($percentage = $_portohelper->getPercentage($_item)) {
                                      if($_product_label_config['sale_label_percent']) {
                                          $product_label .= '<div class="product-label sale-label">'.$percentage.'%'.'</div>';
                                      } else {
                                          $product_label .= '<div class="product-label sale-label">'.$_product_label_config['sale_label_text'].'</div>';
                                      }
                                  }
                              }
                              if($_product_label_config['new_label']) {
                                  $now = date("Y-m-d");
                                  $newsFrom= substr($_item->getData('news_from_date')?$_item->getData('news_from_date'):'',0,10);
                                  $newsTo=  substr($_item->getData('news_to_date')?$_item->getData('news_to_date'):'',0,10);

                                  if ($newsTo != '' || $newsFrom != ''){
                                      if (($newsTo != '' && $newsFrom != '' && $now>=$newsFrom && $now<=$newsTo) || ($newsTo == '' && $now >=$newsFrom) || ($newsFrom == '' && $now<=$newsTo)) {
                                          $product_label .= '<div class="product-label new-label">'.$_product_label_config['new_label_text'].'</div>';
                                      }
                                  }
                              }
                              if($product_label)
                                  echo '<div class="product-labels">'.$product_label.'</div>';
                          ?>
                          <?php if($product_type == 3 || $product_type == 5 || $product_type == 6 || $product_type == 7 || $product_type == 8 || $product_type == 9): ?>
                          <div class="product-item-inner">
                              <div class="product actions product-item-actions">
                                  <div class="actions-primary">
                                      <?php if ($_item->isSaleable()): ?>
                                        <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                            <button class="action tocart primary"
                                                    data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                    type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        <?php else: ?>
                                            <?php
                                                $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                            ?>
                                            <button class="action tocart primary"
                                                    data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                    type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                            </button>
                                        <?php endif; ?>
                                      <?php else: ?>
                                          <?php if ($_item->getIsSalable()): ?>
                                              <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                          <?php else: ?>
                                              <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                          <?php endif; ?>
                                      <?php endif; ?>
                                  </div>
                                  <?php if ($mode == 'grid'): ?>
                                  <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                      <a href="#"
                                         class="action towishlist actions-secondary"
                                         title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                         aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                         data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
                                         data-action="add-to-wishlist"
                                         role="button">
                                          <span><?php echo __('Add to Wish List') ?></span>
                                      </a>
                                  <?php endif; ?>
                                  <?php endif; ?>
                                  <?php if($_category_config['addtocompare']): ?>
                                  <?php
                                  $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                  ?>
                                  <a href="#"
                                     class="action tocompare actions-secondary"
                                     title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                     aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                     data-post='<?php echo $compareHelper->getPostDataParams($_item); ?>'
                                     role="button">
                                      <span><?php echo __('Add to Compare') ?></span>
                                  </a>
                                  <?php endif; ?>
                              </div>
                          </div>
                          <?php endif; ?>
                        </div>
                        <div class="product details product-item-details">
                          <?php
                              $_productNameStripped = $block->stripTags($_item->getName(), null, true);
                          ?>
                          <strong class="product name product-item-name">
                              <a class="product-item-link"
                                 href="<?php echo $_item->getProductUrl() ?>">
                                  <?php echo $_helper->productAttribute($_item, $_item->getName(), 'name'); ?>
                              </a>
                          </strong>

                            <?php if($_category_config['rating_star']): ?>
                            <?php
                                $review_html = $block->getReviewsSummaryHtml($_item, $templateType);
                            ?>
                            <?php if($review_html): ?>
                                <?php echo $review_html; ?>
                            <?php else: ?>
                            <div class="product-reviews-summary short">
                                <div class="rating-summary">
                                    <span class="label"><span>Rating:</span></span>
                                    <div class="rating-result" title="0%">
                                        <span style="width:0"><span>0%</span></span>
                                    </div>
                                </div>
                            </div>
                            <?php endif; ?>
                            <?php endif; ?>

                            <?php if($_category_config['product_price']): ?>
                            <?php echo $block->getProductPriceHtml($_item, $type); ?>
                            <?php endif; ?>
                            <?php if($product_type != 3 && $product_type != 5 && $product_type != 6 && $product_type != 7 && $product_type != 8 && $product_type != 9): ?>
                            <div class="product-item-inner">
                                <div class="product actions product-item-actions">
                                    <?php if ($mode == 'grid'): ?>
                                    <?php if($_category_config['addtowishlist'] && $product_type != 4): ?>
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                        <a href="#"
                                           class="action towishlist actions-secondary"
                                           title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
                                           data-action="add-to-wishlist"
                                           role="button">
                                            <span><?php echo __('Add to Wish List') ?></span>
                                        </a>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                    <div class="actions-primary">
                                        <?php if ($_item->isSaleable()): ?>
                                          <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                              <button class="action tocart primary"
                                                      data-mage-init='{"redirectUrl":{"url":"<?php /* @escapeNotVerified */ echo $block->getAddToCartUrl($_item) ?>"}}'
                                                      type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                  <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                              </button>
                                          <?php else: ?>
                                              <?php
                                                  $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                  $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                              ?>
                                              <button class="action tocart primary"
                                                      data-post='<?php /* @escapeNotVerified */ echo $postData; ?>'
                                                      type="button" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>">
                                                  <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                              </button>
                                          <?php endif; ?>
                                        <?php else: ?>
                                            <?php if ($_item->getIsSalable()): ?>
                                                <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <?php if ($mode == 'grid'): ?>
                                    <?php if($_category_config['addtowishlist'] && $product_type == 4): ?>
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                        <a href="#"
                                           class="action towishlist actions-secondary"
                                           title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
                                           data-action="add-to-wishlist"
                                           role="button">
                                            <span><?php echo __('Add to Wish List') ?></span>
                                        </a>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                    <?php if ($mode == 'list'): ?>
                                    <?php if($_category_config['addtowishlist']): ?>
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                        <a href="#"
                                           class="action towishlist actions-secondary"
                                           title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                           data-post='<?php echo $block->getAddToWishlistParams($_item); ?>'
                                           data-action="add-to-wishlist"
                                           role="button">
                                            <span><?php echo __('Add to Wish List') ?></span>
                                        </a>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                    <?php endif; ?>
                                    <?php if($_category_config['addtocompare']): ?>
                                    <?php
                                    $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                    ?>
                                    <a href="#"
                                       class="action tocompare actions-secondary"
                                       title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                       data-post='<?php echo $compareHelper->getPostDataParams($_item); ?>'
                                       role="button">
                                        <span><?php echo __('Add to Compare') ?></span>
                                    </a>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <?php echo($iterator == count($items)+1) ? '</li>' : '' ?>
                <?php endforeach ?>
            </ol>
        </div>
        <?php echo $block->getPagerHtml() ?>
<?php endif;?>
