<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<form class="form single-subscribe subscribe"
    novalidate
    action="<?php echo $block->getFormActionUrl() ?>"
    method="post"
    data-mage-init='{"validation": {"errorClass": "mage-error"}}'
    id="newsletter-validate-detail-1">
    <div class="field newsletter">
        <div class="control">
          <span class="input-text">
            <input name="email" placeholder="<?php echo __('Email Address'); ?>" type="email" id="newsletter" data-validate="{required:true, 'validate-email':true}"/>
          </span>
          <button class="action subscribe primary" title="<?php echo __('Subscribe') ?>" type="submit">
              <span><?php echo __('Subscribe') ?></span>
          </button>
        </div>
    </div>
</form>
